version: '3'
  services:
    java-server:
      build:
        context: ./
        dockerfile: Dockerfile
      image: java-custom-server
      ports:
        - 8080:8080
      environment:
        - spring.datasource.url=jdbc:mysql://localhost:3306/springproject?useSSL=false
      networks:
        - springmysql-net
      depends_on:
        - mysqldb

    mysqldb:
      image: mysql:5.7
      networks:
        - springmysql-net
      environment:
        - MYSQL_ROOT_PASSWORD=dbmysql
        - MYSQL_DATABASE=springproject

  networks:
    springmysql-net:
